DELETE FROM lang WHERE app_name='polls';
DELETE FROM lang WHERE message_id='polls';
INSERT INTO lang (message_id, app_name, lang, content) VALUES('title','polls','en','Title');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('answer','polls','en','Answer');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('answer has been added to poll','polls','en','Answer has been added to poll');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('add answer to poll','polls','en','Add answer to poll');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('which poll','polls','en','Which poll');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('new poll has been added.  you should now add some answers for this poll','polls','en','New poll has been added.  You should now add some answers for this poll');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('add new poll question','polls','en','Add new poll question');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('enter poll question','polls','en','Enter poll question');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('are you sure want to delete this answer ?','polls','en','Are you sure want to delete this answer ?');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('are you sure want to delete this question ?','polls','en','Are you sure want to delete this question ?');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('answer has been updated','polls','en','Answer has been updated');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('question has been updated','polls','en','Question has been updated');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('poll question','polls','en','Poll question');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('allow users to vote more then once','polls','en','Allow users to vote more then once');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('select current poll','polls','en','Select current poll');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('view poll','polls','en','View poll');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('voting booth administration','polls','en','Voting booth administration');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('show questions','polls','en','Show questions');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('show answers','polls','en','Show answers');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('add answers','polls','en','Add answers');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('add questions','polls','en','Add questions');
INSERT INTO lang (message_id, app_name, lang, content) VALUES('poll settings','polls','en','Poll settings');
