# First we will delete all entries for projects, to prevent dups when updating.                                                                                  
DELETE from lang WHERE app_name='projects';
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('projects','common','en','Projects');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('project preferences','projects','en','Project Preferences');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('please select currency and tax in preferences','projects','en','Please select currency and tax in preferences!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('projects','admin','en','Projects');                                                                
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('projects','projects','en','Projects');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('project','projects','en','Project');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('all open hours','projects','en','All open hours');           
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('all done hours','projects','en','All done hours');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('activity','projects','en','Activity');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('active','projects','en','Active');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('new project','projects','en','New Project');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('addhour','projects','en','Add Hour');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('edit','projects','en','Edit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('activities list','projects','en','Activities List');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('activity list - add','projects','en','Add Activity');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('activity list - edit','projects','en','Edit Activity');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('coordinator','projects','en','Coordinator');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('project name','projects','en','Project Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('number','projects','en','Number');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('add project','projects','en','Add Project');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('update project','projects','en','Update Project');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('status','projects','en','Status');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('title','projects','en','Title');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('userstatistics','projects','en','User Statistics');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('date due','projects','en','Date Due');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('projectstatistics','projects','en','Project Statistics');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('pos','projects','en','Pos');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('projectstatistic','projects','en','Project Statistic');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('admin','projects','en','Admin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('projecthours','projects','en','Project Hours');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('account','projects','en','Account');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('projectbilling','projects','en','Project Billing');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('userstatistic','projects','en','User Statistic');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('projectdelivery','projects','en','Project Delivery');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('hours','projects','en','Hours');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('billedonly','projects','en','Billed only');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('viewhour','projects','en','View Hour');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('copy template','projects','en','Copy Template');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('overall','projects','en','Overall');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('search','projects','en','Search');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('lid','projects','en','Username');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('submit','projects','en','Submit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('date','projects','en','Date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('budget','projects','en','Budget');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('customer','projects','en','Customer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('bookable activities','projects','en','Bookable Activities');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('billable activities','projects','en','Billable Activities');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('billperae','projects','en','Bill per Workunit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('minperae','projects','en','Minutes per Workunit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('project list','projects','en','Project List');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('end_date','projects','en','Date Due');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('project list - edit','projects','en','Edit Project');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('project list - add','projects','en','Add Project');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('project hours - add','projects','en','Add Project Hours');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('return to projects','projects','en','Return to Projects');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('status','projects','en','Status');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('entry_date','projects','en','Entry Date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('nonactive','projects','en','Nonactive');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('description','projects','en','Description');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('template','projects','en','Template');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('remark','projects','en','Job [ Remark ]');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('remarkreq','projects','en','Remark required');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('time','projects','en','Time');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('archiv','projects','en','Archiv');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('done','projects','en','Done');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('open','projects','en','Open');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('billed','projects','en','Billed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('employee','projects','en','Employee');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('edithour','projects','en','Edit Hour');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('number','projects','en','Number');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('deletehour','projects','en','Delete Hour');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('company','projects','en','Company');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('firstname','projects','en','Firstname');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('lastname','projects','en','Lastname');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('select customer','projects','en','Select Customer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('calc','projects','en','Calculate');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('stat','projects','en','Statistic');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('start_date','projects','en','Start Date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('There are no entries','projects','en','There are no entries!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('num','projects','en','Number');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('You have selected an invalid activity','projects','en','You have selected an invalid activity!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('You have selected an invalid date','projects','en','You have selected an invalid date!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('You have to enter a remark','projects','en','You have to enter a remark!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('Are you sure you want to delete this entry','projects','en','Are you sure you want to delete this entry?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('enter your tax','projects','en','Enter tax for work hours');                                                                            
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('return to projects','projects','en','Return to Projects');                                                                              
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('invoice','projects','en','Invoice');                                                                                                    
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('workunits','projects','en','Workunits');                                                                                                
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('no customer selected','projects','en','No customer selected!');                                                                         
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('invoicelist','projects','en','Invoice List');                                                                                           
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('all invoices','projects','en','All Invoices');                                                                                          
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('invoice date','projects','en','Invoice Date');                                                                                          
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('invoice_num','projects','en','Invoice Number');                                                                                         
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('createinvoice','projects','en','Create Invoice');                                                                                       
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('update','projects','en','Update');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('firstname','projects','en','Firstname');                                                                                                
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('lastname','projects','en','Lastname');                                                                                                  
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('company','projects','en','Company');                                                                                                    
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('activity','projects','en','Activity');                                                                                                  
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('active','projects','en','Active');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('select','projects','en','Select');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('aes','projects','en','Workunit');                                                                                                       
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('netto','projects','en','Netto');                                                                                                        
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('sum','projects','en','Sum');                                                                                                            
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('new project','projects','en','New Project');                                                                                            
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('edit','projects','en','Edit');                                                                                                          
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('coordinator','projects','en','Coordinator');                                                                                            
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('number','projects','en','Number');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('status','projects','en','Status');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('title','projects','en','Title');                                                                                                        
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('date due','projects','en','Date Due');                                                                                                  
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('admin','projects','en','Admin');                                                                                                        
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('viewhour','projects','en','View Hour');                                                                                                 
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('copy template','projects','en','Copy Template');                                                                                        
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('search','projects','en','Search');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('submit','projects','en','Submit');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('date','projects','en','Date');                                                                                                          
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('budget','projects','en','Budget');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('customer','projects','en','Customer');                                                                                                  
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('billperae','projects','en','Bill per Workunit');                                                                                        
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('minperae','projects','en','Minutes per Workunit');                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('end_date','projects','en','Date Due');                                                                                                  
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('project hours - edit','projects','en','Edit Project Hours');                                                                            
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('print invoice','projects','en','Print Invoice');                                                                                        
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('status','projects','en','Status');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('entry_date','projects','en','Entry Date');                                                                                              
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('nonactive','projects','en','Nonactive');                                                                                                
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('description','projects','en','Description');                                                                                            
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('remark','projects','en','Job [ Remark ]');                                                                                              
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('time','projects','en','Time');                                                                                                          
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('archiv','projects','en','Archiv');                                                                                                      
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('mwst','projects','en','tax');                                                                                                           
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('done','projects','en','Done');                                                                                                          
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('delivery note','projects','en','Delivery Note');                                                                               
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('all delivery notes','projects','en','ALL Delivery Notes');                                                              
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('delivery','projects','en','Delivery');                                                                                         
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('deliverylist','projects','en','Delivery List');                                                                                
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('all deliverys','projects','en','All Deliverys');                                                                               
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('delivery date','projects','en','Delivery Date');                                                                               
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('delivery_num','projects','en','Delivery Number');                                                                              
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('createdelivery','projects','en','Create Delivery');                                                                            
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('update','projects','en','Update');                                                                                             
REPLACE INTO lang (message_id, app_name, lang, content) VALUES('print delivery','projects','en','Print Delivery');                                                                                              