REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'relogin','ftp','en','logout/relogin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cd','ftp','en','cd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','ftp','en','delete %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'deleted','ftp','en','Succsessfully deleted %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to delete','ftp','en','Failed to delete %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','ftp','en','view');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','ftp','en','save');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save to filemanager','ftp','en','save to filemanager');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','ftp','en','upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'uploaded','ftp','en','Successfully uploaded %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to upload','ftp','en','Failed to upload %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new directory','ftp','en','Create new dir');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to mkdir','ftp','en','Failed to created direcotory %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'empty dirname','ftp','en','Attempt to create a directory with empty name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'module name','ftp','en','Ftp Client');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','ftp','en','Home');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','ftp','en','Username');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','ftp','en','Password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftpserver','ftp','en','Ftp Server');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'connect','ftp','en','Connect');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad connection','ftp','en','Failed to connect to %1 with user %2 and password %3');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','ftp','en','cancel');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','ftp','en','rename %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'renamed','ftp','en','Renamed %1 to %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created directory','ftp','en','Successfully created %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to rename','ftp','en','Failed to rename %1 to %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename from','ftp','en','Rename from');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename to','ftp','en','to');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'confirm delete','ftp','en','Do you really want to delete %1 ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','ftp','en','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'relogin','ftp','de','LogOut/ReLogin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cd','ftp','de','cd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','ftp','de','%1 l&ouml;schen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'deleted','ftp','de','%1 erfolgreich gel&ouml;scht');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to delete','ftp','de','Konnte %1 nicht l&ouml;schen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','ftp','de','Anzeigen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','ftp','de','Speichern');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save to filemanager','ftp','de','In den FileManager speichern');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','ftp','de','Upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'uploaded','ftp','de','%1 erfolgreich hochgeladen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to upload','ftp','de','%1 konnte nicht hochgeladen werden');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new directory','ftp','de','Neues Verzeichnis erstellen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to mkdir','ftp','de','Failed to created direcotory %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'empty dirname','ftp','de','Es wurde versucht, ein Verzeichnis mit leerem Namen anzulegen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'module name','ftp','de','Ftp Client');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','ftp','de','Home');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','ftp','de','Username');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','ftp','de','Password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftpserver','ftp','de','Ftp Server');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'connect','ftp','de','Connect');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad connection','ftp','de','Verbindung zu %1 mit UserNamen %2 und Passwort %3 fehlgeschlagen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','ftp','de','abbrechen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','ftp','de','%1 umbenennen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'renamed','ftp','de','%1 umbenannt in %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created directory','ftp','de','%1 erfolgreich erstellt');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to rename','ftp','de','Konnte %1 nicht in %2 umbenennen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename from','ftp','de','Umbenennen von');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename to','ftp','de','in');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'confirm delete','ftp','de','M”chten Sie %1 wirklich l&ouml;schen ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','ftp','de','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'relogin','ftp','fr','logout/relogin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cd','ftp','fr','cd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','ftp','fr','supprimer %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'deleted','ftp','fr','%1 supprim&eacute; avec succ&egrave;s');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to delete','ftp','fr','Impossible de supprimer %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','ftp','fr','voir');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','ftp','fr','sauver');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save to filemanager','ftp','fr','sauver vers le gestionnaire de fichiers');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','ftp','fr','upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'uploaded','ftp','fr','%1 upload&eacute; avec succ&egrave;s');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to upload','ftp','fr','Impossible d\'uploader %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new directory','ftp','fr','Cr&eacute;er un nouveau r&eacute;pertoire');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to mkdir','ftp','fr','Impossible de cr&eacute;er le r&eacute;pertoire %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'empty dirname','ftp','fr','Essaie de cr&eacute;er un r&eacute;pertoire sans nom');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'module name','ftp','fr','Client Ftp');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','ftp','fr','Home');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','ftp','fr','Utilisateur');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','ftp','fr','Mot de passe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftpserver','ftp','fr','Server Ftp');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'connect','ftp','fr','Connecter');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad connection','ftp','fr','Impossible de se connecter &agrave; %1 avec l\'utilisateur %2 et le mot de passe %3');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','ftp','fr','annuler');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','ftp','fr','renomer %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'renamed','ftp','fr','%1 renom&eacute; en %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created directory','ftp','fr','%1 cr&eacute;&eacute; avec succ&egrave;s');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to rename','ftp','fr','imossible de renomer %1 en %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename from','ftp','fr','Renomer depuis');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename to','ftp','fr','vers');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'confirm delete','ftp','fr','Voulez-vous vraiment supprimer %1 ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','ftp','fr','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'relogin','ftp','kr','·Î±×¾Æ¿ô/Àç·Î±×ÀÎ');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cd','ftp','kr','cd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','ftp','kr','»èÁ¦ %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'deleted','ftp','kr','%1°¡ »èÁ¦µÇ¾ú½À´Ï´Ù.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to delete','ftp','kr','%1¸¦ »èÁ¦ÇÏ´Âµ¥ ¿¡·¯°¡ ¹ß»ýÇÏ¿´½À´Ï´Ù.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','ftp','kr','º¸±â');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','ftp','kr','ÀúÀå');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save to filemanager','ftp','kr','ÆÄÀÏ¸Þ´ÏÀú·Î ÀúÀå');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','ftp','kr','¾÷·Îµå');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'uploaded','ftp','kr','%1¸¦ ¾÷·Îµå Çß½À´Ï´Ù.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to upload','ftp','kr','%1¸¦ ¾÷·Îµå ½ÇÆÐ');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new directory','ftp','kr','»õ µð·ºÅä¸® »ý¼º');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to mkdir','ftp','kr','µð·ºÅä¸® %1 »ý¼ºÇÊÆÐ');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'empty dirname','ftp','kr','ÀÌ¸§ ¾ø´Â µð·ºÅä¸®¸¦ ¸¸µì´Ï´Ù.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'module name','ftp','kr','FTP Å¬¶óÀÌ¾ðÆ®');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','ftp','kr','Á¢¼ÓÁö');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','ftp','kr','»ç¿ëÀÚÀÌ¸§');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','ftp','kr','ÆÐ½º¿öµå');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftpserver','ftp','kr','FTP ¼­¹ö');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'connect','ftp','kr','Á¢¼Ó');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad connection','ftp','kr','%1·Î »ç¿ëÀÚ ID %2 ¿Í ºñ¹Ð¹øÈ£ %3·Î Á¢¼ÓÇÏ´Â ½ÇÆÐÇß½À´Ï´Ù.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','ftp','kr','Ãë¼Ò');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','ftp','kr','ÀÌ¸§¹Ù²Ù±â %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'renamed','ftp','kr','%1 À»  %2·Î ÀÌ¸§À» ¹Ù²å½À´Ï´Ù.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created directory','ftp','kr','%1°¡ ¼º°øÀûÀ¸·Î »ý¼ºµÇ¾ú½À´Ï´Ù.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to rename','ftp','kr','%1 À»  %2À¸·Î ¹Ù²Ù´Âµ¥ ½ÇÆÐÇß½À´Ï´Ù.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename from','ftp','kr','ÀÌ¸§ ¹Ù²Þ');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename to','ftp','kr','À¸·Î');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'confirm delete','ftp','kr','%1¸¦ Á¤¸» »èÁ¦ÇÏ½Ã°Ú½À´Ï±î ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','ftp','kr','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'relogin','ftp','nl','afmelden/opnieuw aanmelden');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cd','ftp','nl','cd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','ftp','nl','verwijder %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'deleted','ftp','nl','%1 met succes verwijderd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to delete','ftp','nl','Verwijderen van %1 is mislukt');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','ftp','nl','weergeven');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','ftp','nl','opslaan');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save to filemanager','ftp','nl','oplaan naar bestandsbeheerder');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','ftp','nl','upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'uploaded','ftp','nl','%1 met success ge-upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to upload','ftp','nl','Upload van %1 is mislukt');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new directory','ftp','nl','Maak een nieuwe folder');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to mkdir','ftp','nl','Maken van folder %1 is mislukt');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'empty dirname','ftp','nl','Poging om een folder zonder naam te maken');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'module name','ftp','nl','Ftp Client');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','ftp','nl','Home');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','ftp','nl','Gebruikersnaam');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','ftp','nl','Wachtwoord');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftpserver','ftp','nl','Ftp Server');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'connect','ftp','nl','Verbinden');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad connection','ftp','nl','Verbinden met server %1 als gebruiker %2 met wachtwoord %3 is mislukt');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','ftp','nl','annuleren');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','ftp','nl','%1 hernoemen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'renamed','ftp','nl','%1 hernoemd als %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created directory','ftp','nl','%1 met succes gemaakt');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to rename','ftp','nl','Hernoemen van %1 als %2 is mislukt');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename from','ftp','nl','Hernoem');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename to','ftp','nl','als');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'confirm delete','ftp','nl','Wilt u %1 echt verwijderen?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','ftp','nl','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'relogin','ftp','no','logout/relogin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cd','ftp','no','cd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','ftp','no','slette %');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'deleted','ftp','no','Slettet %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to delete','ftp','no','Kunne ikke slette %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','ftp','no','vis');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','ftp','no','lagre');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save to filemanager','ftp','no','lagre til filmanager');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','ftp','no','upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'uploaded','ftp','no','Suksessfullt uploaded %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to upload','ftp','no','Kunne ikke uploade %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new directory','ftp','no','Laget nytt dir');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to mkdir','ftp','no','Kunne ikke lage nytt direcotory %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'empty dirname','ftp','no','Forsøk å lage et directory uten navn');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'module name','ftp','no','Ftp Klient');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','ftp','no','Home');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','ftp','no','Brukernavne');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','ftp','no','Passord');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftpserver','ftp','no','Ftp Server');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'connect','ftp','no','Connect');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad connection','ftp','no','Kunne ikke connecte til %1 med bruker %2 og passord %3');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','ftp','no','avbryt');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','ftp','no','rename %');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'renamed','ftp','no','Renamed %1 til %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created directory','ftp','no','Laget %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to rename','ftp','no','Kunne ikke rename %1 til %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename from','ftp','no','Rename fra');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename to','ftp','no','til');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'confirm delete','ftp','no','Vil du virkelig slette %1 ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','ftp','no','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'relogin','ftp','sp','logout/relogin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cd','ftp','sp','cd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','ftp','sp','borrar %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'deleted','ftp','sp','Exitosamente borrado %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to delete','ftp','sp','Fallo al borrar %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','ftp','sp','ver');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','ftp','sp','grabar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save to filemanager','ftp','sp','grabar al manejador de archivo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','ftp','sp','subir');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'uploaded','ftp','sp','Exitosamente subido %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to upload','ftp','sp','Fallo al subir %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new directory','ftp','sp','Crear nuevo directorio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to mkdir','ftp','sp','Fallo al crear directorio %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'empty dirname','ftp','sp','Intento de crear un directorio sin nombre');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'module name','ftp','sp','Cliente Ftp');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','ftp','sp','Home');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','ftp','sp','Usuario');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','ftp','sp','Contraseña');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftpserver','ftp','sp','Servidor Ftp');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'connect','ftp','sp','Conectar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad connection','ftp','sp','Fallo al conectar a %1 con el usuario %2 y contraseña %3');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','ftp','sp','cancelar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','ftp','sp','renombrar %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'renamed','ftp','sp','Renombrar %1 a %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created directory','ftp','sp','Exitosamente creado %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to rename','ftp','sp','Fallo al renombrar %1 a %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename from','ftp','sp','Renombrar desde');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename to','ftp','sp','a');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'confirm delete','ftp','sp','Realmente desea borrar %1 ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','ftp','sp','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'relogin','ftp','br','logout/relogin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cd','ftp','br','cd');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','ftp','br','delete %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'deleted','ftp','br','Succsessfully deleted %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to delete','ftp','br','Failed to delete %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','ftp','br','view');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','ftp','br','save');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save to filemanager','ftp','br','save to filemanager');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','ftp','br','upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'uploaded','ftp','br','Successfully uploaded %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to upload','ftp','br','Failed to upload %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new directory','ftp','br','Create new dir');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to mkdir','ftp','br','Failed to created direcotory %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'empty dirname','ftp','br','Attempt to create a directory with empty name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'module name','ftp','br','Ftp Client');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','ftp','br','Home');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','ftp','br','Username');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','ftp','br','Password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftpserver','ftp','br','Ftp Server');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'connect','ftp','br','Connect');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad connection','ftp','br','Failed to connect to %1 with user %2 and password %3');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','ftp','br','cancel');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','ftp','br','rename %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'renamed','ftp','br','Renamed %1 to %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created directory','ftp','br','Successfully created %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'failed to rename','ftp','br','Failed to rename %1 to %2');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename from','ftp','br','Rename from');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename to','ftp','br','to');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'confirm delete','ftp','br','Do you really want to delete %1 ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','ftp','br','');
