REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'forums','forum','en','Forums');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'return to forums','forum','en','Return to Forums');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'return to admin','forum','en','Return to Admin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new forum','forum','en','New Forum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new category','forum','en','New Category');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no category','forum','en','No Category');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'edit','forum','en','Edit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'category name','forum','en','Category Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'category description','forum','en','Category Description');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'forum name','forum','en','Forum Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'forum description','forum','en','Forum Description');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add forum','forum','en','Add Forum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update forum','forum','en','Update Forum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update category','forum','en','Update Category');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'belongs to category','forum','en','Belongs to Category');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add category','forum','en','Add Category');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new category','forum','en','Create New Category');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create new forum','forum','en','Create New Forum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'current categories and sub forums','forum','en','Current Categories and Sub Forums');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new topic','forum','en','New Topic');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'admin','forum','en','Admin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'topic','forum','en','Topic');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reply to this message','forum','en','Reply to this message');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view threads','forum','en','View Threads');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'collapse threads','forum','en','Collapse Threads');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'search','forum','en','Search');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'submit','forum','en','Submit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reply','forum','en','Reply');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'author','forum','en','Author');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date','forum','en','Date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'replies','forum','en','Replies');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'latest reply','forum','en','Latest Reply');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your name','forum','en','Your Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your email','forum','en','Your Email');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','forum','en','Subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'email replies to this thread, to the address above','forum','en','Email replies to this thread, to the address above');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no messages available!','forum','en','No messages available!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no messages available!','forum','en','No messages available!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'forums','forum','fi','Forums');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new topic','forum','fi','New Topic');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'admin','forum','fi','Admin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'topic','forum','fi','Topic');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reply to this message','forum','fi','Reply to this message');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view threads','forum','fi','View Threads');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'collapse threads','forum','fi','Collapse Threads');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'search','forum','fi','Search');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'submit','forum','fi','Submit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reply','forum','fi','Reply');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'author','forum','fi','Author');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date','forum','fi','Date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'replies','forum','fi','Replies');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'latest reply','forum','fi','Latest Reply');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your name','forum','fi','Your Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your email','forum','fi','Your Email');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','forum','fi','Subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'email replies to this thread, to the address above','forum','fi','Email replies to this thread, to the address above');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no messages available!','forum','fi','No messages available!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no messages available!','forum','fi','No messages available!');
