//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="cUnnectorOutlookAddIn.Properties.Resources.get_ResourceManager():System.Resources" +
    ".ResourceManager")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="cUnnectorOutlookAddIn.Properties.Resources.get_Culture():System.Globalization.Cul" +
    "tureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="cUnnectorOutlookAddIn.Properties.Resources.set_Culture(System.Globalization.Cultu" +
    "reInfo):Void")]

namespace cUnnectorOutlookAddIn.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cUnnectorOutlookAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap appointments {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("appointments", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap contacts {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("contacts", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap daterange {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("daterange", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap error {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("error", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap error_small {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("error_small", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("folder", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap history {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("history", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap history_clear {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("history_clear", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap info_small {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("info_small", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap reload {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("reload", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap reload32 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("reload32", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap remote {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("remote", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap settings_btn {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("settings_btn", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap start_btn {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("start_btn", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap status_btn {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("status_btn", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap stop_btn {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("stop_btn", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap sync_btn {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sync_btn", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap sync16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sync16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap sync16_mask {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("sync16_mask", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap syncDone {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("syncDone", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap syncRunning {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("syncRunning", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap syncRunning2 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("syncRunning2", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap tasks {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("tasks", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap time {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("time", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap user {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("user", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap warning_small {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("warning_small", resourceCulture)));
            }
        }
    }
}
