REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','en','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','en','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','en','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','en','Group');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','en','Assigned to');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','tts','en','Assign to');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','en','Opened by');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','en','Date opened');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','en','Subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','en','New ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','en','View all tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','en','View only open tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','en','No tickets found');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','en','Status/Date closed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','en','Add new ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','en','Detail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','en','Priority');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','en','Add ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','en','Clear form');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','en','No subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','en','view job detail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','en','Assigned from');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','en','Open date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','en','Close date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','en','Details');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','en','Additional notes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','en','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','en','Update');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','en','Close');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','en','In progress');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','en','Closed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','en','ReOpen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','en','ReOpen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','de','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','de','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','de','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','de','Gruppe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','de','Zugewiesen an');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','tts','de','Zuweisen an');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','de','Angelegt von');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','de','Angelegt am');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','de','Betreff');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','de','Neues Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','de','Alle Tickets anzeigen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','de','Nur offene Tickets anzeigen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','de','Keine Tickets gefunden');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','de','Status/Schlie&szlig;datum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','de','Neues Ticket hinzuf&uuml;gen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','de','Detail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','de','Priorit&auml;t');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','de','Ticket hinzuf&uuml;gen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','de','Eingabe l&ouml;schen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','de','Kein Betreff');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','de','Details anzeigen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','de','Zugewiesen von');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','de','Angelegt am');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','de','Geschlossen am');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','de','Details');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','de','Zus&auml;tzliche Notizen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','de','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','de','Aktualisieren');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','de','Schlie&szlig;en');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','de','In Bearbeitung');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','de','Geschlossen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','de','Wieder &ouml;ffnen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','de','Wieder &ouml;ffnen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','br','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','br','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','br','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','br','Grupo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','br','Atribuido a');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','br','Aberto por');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','br','Data abertura');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','br','Assunto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','br','Novo ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','br','Visualizar todos tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','br','Ver todos tickets abertos');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','br','Nao foram encontrados tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','br','Estado/Data fechado');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','br','Adicionar novo ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','br','Detalhes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','br','Prioridade');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','br','Criar ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','br','Limpar formulario');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','br','Sem assunto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','br','Ver detalhes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','br','Atribuido de');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','br','Data abertura');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','br','Data fechamento');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','br','Detalhes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','br','Notas adicionais');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','br','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','br','Atualize');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','br','Feche');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','br','Em progresso');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','br','Fechado');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','br','Reaberto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','br','Reaberto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','fr','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','fr','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','fr','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','fr','Groupe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','fr','Assign&eacute; &agrave;');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','fr','Ouvert par');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','fr','Date d\'ouverture');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','fr','Sujet');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','fr','Nouveau ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','fr','Voir tous les tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','fr','Voir uniquement les tickets ouverts');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','fr','Aucun ticket trouv&eacute;');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','fr','Etat/Date de fermeture');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','fr','Ajouter un nouveau ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','fr','D&eacute;tail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','fr','Priorit&eacute;');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','fr','Ajouter un ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','fr','Effacer le formulaire');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','fr','Pas de sujet');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','fr','voir le d&eacute;tail du travail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','fr','Assign&eacute; par');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','fr','Date d\'ouverture');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','fr','Date de fermeture');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','fr','D&eacute;tails');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','fr','Notes suppl&eacute;mentaires');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','fr','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','fr','Mettre &agrave; jour');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','fr','Fermer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','fr','En cours');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','fr','Ferm&eacute;');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','fr','ReOuvert');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','fr','ReOuvert');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','kr','에러리포트 시스템');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','kr','작업');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','kr','중요도');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','kr','그룹');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','kr','할당');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','kr','작성자');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','kr','작성일');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','kr','제목');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','kr','새 작업');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','kr','모든 작업보기');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','kr','활성된 작업보기');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','kr','작업이 없음');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','kr','비활성된 상태/날짜');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','kr','새 작업추가');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','kr','설명');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','kr','중요도');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','kr','새작업 추가');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','kr','재작성');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','kr','제목없음');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','kr','작업 내용보기');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','kr','작업자');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','kr','시작 날짜');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','kr','종료 날짜');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','kr','설명');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','kr','내용 추가');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','kr','확인');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','kr','업데이트');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','kr','종료');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','kr','진행중');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','kr','종료됨');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','kr','재시작');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','kr','재시작');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','nl','Problemen Registratie Systeem');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','nl','Melding');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','nl','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','nl','Groep');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','nl','Toegewezen aan');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','tts','nl','Toewijzen aan');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','nl','Aangenomen door');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','nl','Aanmaak datum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','nl','Onderwerp');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','nl','Nieuwe melding');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','nl','Geef alle meldingen weer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','nl','Geef alleen openstaande meldingen weer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','nl','Geen meldingen gevonden');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','nl','Status/Datum gesloten');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','nl','Voeg nieuwe melding toe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','nl','Detail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','nl','Prioriteit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','nl','Voeg melding toe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','nl','Formulier wissen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','nl','Geen onderwerp');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','nl','Details werkzaamheden weergeven');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','nl','Toegewezen door');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','nl','Datum opening');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','nl','Datum sluiting');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','nl','Details');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','nl','Opmerkingen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','nl','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','nl','Bijwerken');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','nl','Sluiten');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','nl','In uitvoering');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','nl','Gesloten');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','nl','Heropenen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','nl','Heropenen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','sp','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','sp','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','sp','Prioridad');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','sp','Groupo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','sp','Asignado a');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','tts','sp','Asignar a');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','sp','Abierto por');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','sp','Fecha apertura');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','sp','Asunto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','sp','Nuevo ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','sp','Ver todos los tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','sp','Ver solo los tickets abiertos');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','sp','No se encontraron tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','sp','Estado/Fecha cierre');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','sp','Agregar nuevo ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','sp','Detalle');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','sp','Prioridad');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','sp','Agregar ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','sp','Limpiar formulario');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','sp','Sin asunto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','sp','ver detalle del trabajo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','sp','Asignado desde');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','sp','Fecha apertura');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','sp','Fecha cierre');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','sp','Detalles');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','sp','Notas adicionales');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','sp','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','sp','Actualizar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','sp','Cerrar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','sp','En progreso');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','sp','Cerrado');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','sp','ReAbierto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','sp','ReAbierto');
