REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','','en','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','','en','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','','en','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','','en','Group');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','','en','Assigned to');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','','en','Assign to');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','','en','Opened by');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','','en','Date opened');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','','en','Subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','','en','New ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','','en','View all tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','','en','View only open tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','','en','No tickets found');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','','en','Status/Date closed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','','en','Add new ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','','en','Detail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','','en','Priority');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','','en','Add ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','','en','Clear form');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','','en','No subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','','en','view job detail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','','en','Assigned from');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','','en','Open date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','','en','Close date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','','en','Details');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','','en','Additional notes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','','en','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','','en','Update');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','','en','Close');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','','en','In progress');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','','en','Closed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','en','ReOpen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','en','ReOpen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','','de','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','','de','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','','de','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','','de','Gruppe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','','de','Zugewiesen an');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','','de','Zuweisen an');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','','de','Angelegt von');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','','de','Angelegt am');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','','de','Betreff');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','','de','Neues Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','','de','Alle Tickets anzeigen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','','de','Nur offene Tickets anzeigen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','','de','Keine Tickets gefunden');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','','de','Status/Schlie&szlig;datum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','','de','Neues Ticket hinzuf&uuml;gen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','','de','Detail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','','de','Priorit&auml;t');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','','de','Ticket hinzuf&uuml;gen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','','de','Eingabe l&ouml;schen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','','de','Kein Betreff');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','','de','Details anzeigen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','','de','Zugewiesen von');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','','de','Angelegt am');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','','de','Geschlossen am');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','','de','Details');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','','de','Zus&auml;tzliche Notizen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','','de','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','','de','Aktualisieren');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','','de','Schlie&szlig;en');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','','de','In Bearbeitung');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','','de','Geschlossen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','de','Wieder &ouml;ffnen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','de','Wieder &ouml;ffnen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','','br','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','','br','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','','br','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','','br','Grupo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','','br','Atribuido a');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','','br','Aberto por');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','','br','Data abertura');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','','br','Assunto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','','br','Novo ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','','br','Visualizar todos tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','','br','Ver todos tickets abertos');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','','br','Nao foram encontrados tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','','br','Estado/Data fechado');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','','br','Adicionar novo ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','','br','Detalhes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','','br','Prioridade');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','','br','Criar ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','','br','Limpar formulario');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','','br','Sem assunto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','','br','Ver detalhes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','','br','Atribuido de');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','','br','Data abertura');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','','br','Data fechamento');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','','br','Detalhes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','','br','Notas adicionais');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','','br','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','','br','Atualize');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','','br','Feche');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','','br','Em progresso');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','','br','Fechado');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','br','Reaberto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','br','Reaberto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','','fr','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','','fr','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','','fr','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','','fr','Groupe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','','fr','Assign&eacute; &agrave;');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','','fr','Ouvert par');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','','fr','Date d\'ouverture');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','','fr','Sujet');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','','fr','Nouveau ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','','fr','Voir tous les tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','','fr','Voir uniquement les tickets ouverts');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','','fr','Aucun ticket trouv&eacute;');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','','fr','Etat/Date de fermeture');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','','fr','Ajouter un nouveau ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','','fr','D&eacute;tail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','','fr','Priorit&eacute;');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','','fr','Ajouter un ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','','fr','Effacer le formulaire');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','','fr','Pas de sujet');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','','fr','voir le d&eacute;tail du travail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','','fr','Assign&eacute; par');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','','fr','Date d\'ouverture');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','','fr','Date de fermeture');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','','fr','D&eacute;tails');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','','fr','Notes suppl&eacute;mentaires');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','','fr','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','','fr','Mettre &agrave; jour');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','','fr','Fermer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','','fr','En cours');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','','fr','Ferm&eacute;');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','fr','ReOuvert');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','fr','ReOuvert');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','','kr','에러리포트 시스템');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','','kr','작업');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','','kr','중요도');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','','kr','그룹');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','','kr','할당');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','','kr','작성자');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','','kr','작성일');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','','kr','제목');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','','kr','새 작업');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','','kr','모든 작업보기');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','','kr','활성된 작업보기');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','','kr','작업이 없음');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','','kr','비활성된 상태/날짜');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','','kr','새 작업추가');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','','kr','설명');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','','kr','중요도');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','','kr','새작업 추가');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','','kr','재작성');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','','kr','제목없음');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','','kr','작업 내용보기');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','','kr','작업자');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','','kr','시작 날짜');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','','kr','종료 날짜');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','','kr','설명');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','','kr','내용 추가');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','','kr','확인');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','','kr','업데이트');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','','kr','종료');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','','kr','진행중');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','','kr','종료됨');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','kr','재시작');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','kr','재시작');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','','nl','Problemen Registratie Systeem');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','','nl','Melding');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','','nl','Prio');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','','nl','Groep');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','','nl','Toegewezen aan');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','','nl','Toewijzen aan');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','','nl','Aangenomen door');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','','nl','Aanmaak datum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','','nl','Onderwerp');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','','nl','Nieuwe melding');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','','nl','Geef alle meldingen weer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','','nl','Geef alleen openstaande meldingen weer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','','nl','Geen meldingen gevonden');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','','nl','Status/Datum gesloten');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','','nl','Voeg nieuwe melding toe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','','nl','Detail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','','nl','Prioriteit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','','nl','Voeg melding toe');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','','nl','Formulier wissen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','','nl','Geen onderwerp');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','','nl','Details werkzaamheden weergeven');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','','nl','Toegewezen door');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','','nl','Datum opening');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','','nl','Datum sluiting');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','','nl','Details');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','','nl','Opmerkingen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','','nl','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','','nl','Bijwerken');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','','nl','Sluiten');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','','nl','In uitvoering');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','','nl','Gesloten');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','nl','Heropenen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','nl','Heropenen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','','sp','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','','sp','Ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'prio','','sp','Prioridad');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group','','sp','Groupo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','','sp','Asignado a');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','','sp','Asignar a');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','','sp','Abierto por');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','','sp','Fecha apertura');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','','sp','Asunto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','','sp','Nuevo ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','','sp','Ver todos los tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','','sp','Ver solo los tickets abiertos');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','','sp','No se encontraron tickets');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','','sp','Estado/Fecha cierre');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','','sp','Agregar nuevo ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'detail','','sp','Detalle');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','','sp','Prioridad');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','','sp','Agregar ticket');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','','sp','Limpiar formulario');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','','sp','Sin asunto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','','sp','ver detalle del trabajo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','','sp','Asignado desde');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'open date','','sp','Fecha apertura');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close date','','sp','Fecha cierre');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'details','','sp','Detalles');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','','sp','Notas adicionales');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','','sp','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','','sp','Actualizar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'close','','sp','Cerrar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','','sp','En progreso');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'closed','','sp','Cerrado');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','sp','ReAbierto');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','','sp','ReAbierto');
