INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','en','Trouble Ticket System');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','en','Ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','en','Prio');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','en','Group');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','en','Assigned to');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','tts','en','Assign to');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','en','Opened by');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','en','Date opened');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','en','Subject');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','en','New ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','en','View all tickets');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','en','View only open tickets');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','en','No tickets found');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','en','Status/Date closed');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','en','Add new ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','en','Detail');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','en','Priority');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','en','Add ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','en','Clear form');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','en','No subject');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','en','view job detail');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','en','Assigned from');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','en','Open date');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','en','Close date');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','en','Details');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','en','Additional notes');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','en','OK');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','en','Update');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','en','Close');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','en','In progress');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','en','Closed');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','en','ReOpen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'Ticket assigned to x','tts','en','Ticket assigned to %1');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','de','Trouble Ticket System');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','de','Ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','de','Prio');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','de','Gruppe');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','de','Zugewiesen an');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','tts','de','Zuweisen an');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','de','Angelegt von');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','de','Angelegt am');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','de','Betreff');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','de','Neues Ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','de','Alle Tickets anzeigen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','de','Nur offene Tickets anzeigen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','de','Keine Tickets gefunden');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','de','Status/Schlie&szlig;datum');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','de','Neues Ticket hinzuf&uuml;gen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','de','Detail');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','de','Priorit&auml;t');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','de','Ticket hinzuf&uuml;gen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','de','Eingabe l&ouml;schen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','de','Kein Betreff');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','de','Details anzeigen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','de','Zugewiesen von');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','de','Angelegt am');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','de','Geschlossen am');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','de','Details');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','de','Zus&auml;tzliche Notizen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','de','OK');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','de','Aktualisieren');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','de','Schlie&szlig;en');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','de','In Bearbeitung');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','de','Geschlossen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','de','Wieder &ouml;ffnen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','de','Wieder &ouml;ffnen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','br','Trouble Ticket System');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','br','Ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','br','Prio');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','br','Grupo');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','br','Atribuido a');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','br','Aberto por');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','br','Data abertura');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','br','Assunto');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','br','Novo ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','br','Visualizar todos tickets');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','br','Ver todos tickets abertos');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','br','Nao foram encontrados tickets');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','br','Estado/Data fechado');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','br','Adicionar novo ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','br','Detalhes');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','br','Prioridade');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','br','Criar ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','br','Limpar formulario');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','br','Sem assunto');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','br','Ver detalhes');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','br','Atribuido de');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','br','Data abertura');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','br','Data fechamento');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','br','Detalhes');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','br','Notas adicionais');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','br','OK');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','br','Atualize');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','br','Feche');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','br','Em progresso');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','br','Fechado');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','br','Reaberto');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','br','Reaberto');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','fr','Trouble Ticket System');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','fr','Ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','fr','Prio');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','fr','Groupe');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','fr','Assign&eacute; &agrave;');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','fr','Ouvert par');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','fr','Date d\'ouverture');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','fr','Sujet');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','fr','Nouveau ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','fr','Voir tous les tickets');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','fr','Voir uniquement les tickets ouverts');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','fr','Aucun ticket trouv&eacute;');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','fr','Etat/Date de fermeture');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','fr','Ajouter un nouveau ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','fr','D&eacute;tail');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','fr','Priorit&eacute;');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','fr','Ajouter un ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','fr','Effacer le formulaire');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','fr','Pas de sujet');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','fr','voir le d&eacute;tail du travail');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','fr','Assign&eacute; par');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','fr','Date d\'ouverture');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','fr','Date de fermeture');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','fr','D&eacute;tails');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','fr','Notes suppl&eacute;mentaires');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','fr','OK');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','fr','Mettre &agrave; jour');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','fr','Fermer');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','fr','En cours');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','fr','Ferm&eacute;');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','fr','ReOuvert');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','fr','ReOuvert');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','kr','에러리포트 시스템');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','kr','작업');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','kr','중요도');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','kr','그룹');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','kr','할당');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','kr','작성자');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','kr','작성일');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','kr','제목');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','kr','새 작업');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','kr','모든 작업보기');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','kr','활성된 작업보기');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','kr','작업이 없음');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','kr','비활성된 상태/날짜');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','kr','새 작업추가');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','kr','설명');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','kr','중요도');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','kr','새작업 추가');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','kr','재작성');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','kr','제목없음');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','kr','작업 내용보기');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','kr','작업자');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','kr','시작 날짜');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','kr','종료 날짜');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','kr','설명');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','kr','내용 추가');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','kr','확인');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','kr','업데이트');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','kr','종료');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','kr','진행중');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','kr','종료됨');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','kr','재시작');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','kr','재시작');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','nl','Problemen Registratie Systeem');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','nl','Melding');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','nl','Prio');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','nl','Groep');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','nl','Toegewezen aan');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','tts','nl','Toewijzen aan');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','nl','Aangenomen door');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','nl','Aanmaak datum');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','nl','Onderwerp');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','nl','Nieuwe melding');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','nl','Geef alle meldingen weer');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','nl','Geef alleen openstaande meldingen weer');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','nl','Geen meldingen gevonden');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','nl','Status/Datum gesloten');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','nl','Voeg nieuwe melding toe');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','nl','Detail');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','nl','Prioriteit');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','nl','Voeg melding toe');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','nl','Formulier wissen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','nl','Geen onderwerp');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','nl','Details werkzaamheden weergeven');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','nl','Toegewezen door');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','nl','Datum opening');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','nl','Datum sluiting');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','nl','Details');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','nl','Opmerkingen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','nl','OK');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','nl','Bijwerken');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','nl','Sluiten');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','nl','In uitvoering');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','nl','Gesloten');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','nl','Heropenen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','nl','Heropenen');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','tts','sp','Trouble Ticket System');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ticket','tts','sp','Ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'prio','tts','sp','Prioridad');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group','tts','sp','Groupo');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned to','tts','sp','Asignado a');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assign to','tts','sp','Asignar a');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'opened by','tts','sp','Abierto por');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date opened','tts','sp','Fecha apertura');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','tts','sp','Asunto');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new ticket','tts','sp','Nuevo ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view all tickets','tts','sp','Ver todos los tickets');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view only open tickets','tts','sp','Ver solo los tickets abiertos');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no tickets found','tts','sp','No se encontraron tickets');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'status/date closed','tts','sp','Estado/Fecha cierre');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add new ticket','tts','sp','Agregar nuevo ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'detail','tts','sp','Detalle');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'priority','tts','sp','Prioridad');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ticket','tts','sp','Agregar ticket');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','tts','sp','Limpiar formulario');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','tts','sp','Sin asunto');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view job detail','tts','sp','ver detalle del trabajo');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'assigned from','tts','sp','Asignado desde');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'open date','tts','sp','Fecha apertura');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close date','tts','sp','Fecha cierre');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'details','tts','sp','Detalles');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'additional notes','tts','sp','Notas adicionales');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ok','tts','sp','OK');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'update','tts','sp','Actualizar');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'close','tts','sp','Cerrar');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'in progress','tts','sp','En progreso');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'closed','tts','sp','Cerrado');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','sp','ReAbierto');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reopen','tts','sp','ReAbierto');
