//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="cUnnectorStandaloneApplication.Properties.Resources.get_ResourceManager():System." +
    "Resources.ResourceManager")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="cUnnectorStandaloneApplication.Properties.Resources.get_Culture():System.Globaliz" +
    "ation.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="cUnnectorStandaloneApplication.Properties.Resources.set_Culture(System.Globalizat" +
    "ion.CultureInfo):Void")]

namespace cUnnectorStandaloneApplication.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cUnnectorStandaloneApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap error {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("error", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap error_small {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("error_small", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap history {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("history", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap history_clear {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("history_clear", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap info_small {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("info_small", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap reload {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("reload", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap reload32 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("reload32", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap syncDone {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("syncDone", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap syncRunning {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("syncRunning", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap syncRunning2 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("syncRunning2", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap warning_small {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("warning_small", resourceCulture)));
            }
        }
    }
}
